# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_solicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='persona',
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
